#!/bin/bash
#
# @license	http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author	OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @author	Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
# @copyright Copyright (c) 2012 Marcel Beck
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
	configure)

		########################################################################
		# Set the default settings of the autoshutdown package to those
		# expected by OpenMediaVault.
		########################################################################
		/bin/chmod +x /etc/init.d/autoshutdown

		update-rc.d autoshutdown defaults
		if [ -z "$2" ]; then
			echo "Updating init script links and actions"
			invoke-rc.d --force autoshutdown stop
			update-rc.d autoshutdown disable &>/dev/null
		fi

		if [ ! -f /etc/autoshutdown.conf ];
		then
			cp /etc/autoshutdown.default /etc/autoshutdown.conf
		fi

		if [ -f /etc/rsyslog.d/autoshutdownlog.conf ];
		then
			rm -f /etc/rsyslog.d/autoshutdownlog.conf
		fi

		########################################################################
		#  Update the configuration.
		#	<config>
		#		<services>
		#			<autoshutdown>
		#				<enable>0</enable>
		#				<cycles>6</cycles>
		#				<sleep>180</sleep>
		#				<range>2..254</range>
        #				<shutdowncommand>2..254</shutdowncommand>
		#				<checkclockactive>0</checkclockactive>
		#				<uphours-begin>6</uphours-begin>
		#				<uphours-end>20</uphours-end>
		#				<nsocketnumbers>21,22,80,139,445,3689,6991,9091,49152</nsocketnumbers>
		#				<uldlcheck>1</uldlcheck>
		#				<uldlrate>50</uldlrate>
		#				<loadaveragecheck>0</loadaveragecheck>
		#				<loadaverage>40</loadaverage>
		#				<syslog>1</syslog>
		#				<verbose>0</verbose>
		#				<fake>0</fake>
		#				<extraoptions></extraoptions>
		#			</autoshutdown>
		#		</services>
		#	</config>
		########################################################################

		# Remove old configuration data
		omv_config_delete "/config/services/autoshutdown"
		omv_config_delete "/config/zeroconf/services/autoshutdown"

		echo "Initialize configuration"

		object="<enable>0</enable>"
		object="${object}<cycles>6</cycles>"
		object="${object}<sleep>180</sleep>"
		object="${object}<range>2..254</range>"
        object="${object}<shutdowncommand>0</shutdowncommand>"
		object="${object}<checkclockactive>0</checkclockactive>"
		object="${object}<uphours-begin>6</uphours-begin>"
		object="${object}<uphours-end>20</uphours-end>"
		object="${object}<nsocketnumbers>21,22,80,139,445,3689,6991,9091,49152</nsocketnumbers>"
		object="${object}<uldlcheck>1</uldlcheck>"
		object="${object}<uldlrate>50</uldlrate>"
		object="${object}<loadaveragecheck>0</loadaveragecheck>"
		object="${object}<loadaverage>40</loadaverage>"
		object="${object}<syslog>1</syslog>"
		object="${object}<verbose>0</verbose>"
		object="${object}<fake>0</fake>"
		object="${object}<extraoptions></extraoptions>"

		omv_config_add_element "/config/services" "autoshutdown" "${object}" true

	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
