#!/bin/bash
#
# @license  http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2013-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)

        SERVICE_XPATH_NAME="autoshutdown"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

		echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.autoshutdown"
        if [ -n "$2" ]; then
            deb-systemd-helper disable ${SERVICE_XPATH_NAME}.service >/dev/null || true
            deb-systemd-invoke stop ${SERVICE_XPATH_NAME}.service >/dev/null || true
			omv-confdbadm migrate "conf.service.autoshutdown" "${2}"
        fi

        omv-mkconf autoshutdown

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
