#!/bin/bash
#==============================================================================
#
#  FILE         : autoshutdown
#  DESCRIPTION  : Shuts-down a server based on a set of configurable checks.
#  REQUIREMENTS : Debian / Ubuntu-based system.
#  BUGS         : If you find any: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown
#  AUTHOR       : Solo0815 - R. Lindlein (Ubuntu-Port, OMV-Changes)
#                 based on autoshutdown.sh v0.7.008 by chrikai, see:
#                 https://sourceforge.net/apps/phpbb/freenas/viewtopic.php?f=12&t=2158&start=60
#
#==============================================================================

set -euo pipefail

######## VARIABLE DEFINITION ########
# Variables that normal users should normally not define - PowerUsers can do it
# here or add it to the config.
LPREPEAT=5                # Number of test cycles for finding and active
                          # LOADPROCNAMES-Process (default=5).
TPREPEAT=5                # Number of test cycles for finding and active
                          # TEMPPROCNAMES-Process (default=5).

############## LOGGING ##############
DEBUG="false"             # Default debug logging mode (see VERBOSE).

######## STORAGE DEFINITION #########
declare -A NIC_TO_IP      # Associative array for storing _check_networkconfig
                          # network interface to IP address mappings.
declare -A PINGLIST_IFACE # Associative array for storing _ping_range network
                          # interface IP addresses.
declare -A P_HDDIO_DEVS   # Associative array for storing _check_hddio read,
                          # wrtn and epoch values.
declare -A P_UL_DL_RATE   # Associative array for storing _check_ul_dl_rate a
                          # network interface tx, rx and epoch values.

######## CONSTANT DEFINITION ########
                          # Autoshutdown configuration.
readonly CONFIG="${1:-/etc/autoshutdown.conf}"
                          # Autoshutdown default configuration.
readonly DEFAULT_CONFIG="${2:-/etc/autoshutdown.default}"

######## FUNCTION DECLARATION ########

###############################################################################
#
#   Name       : _log
#   Parameters : $1 : Log message in format "PRIORITY: MESSAGE".
#              : $2 : 'force' will force logging to Syslog and sent to stderr.
#   Globals    : $FAKE       : Are we running in fake mode. ('true' or 'false')
#              : $SYSLOG     : Should logging to to Syslog. ('true' or 'false')
#              : $LOG_STDOUT : Suppress logging to stdout. Set 'false' in a
#                              systemd service. (default 'true')
#   Return     : 0 on success.
#
_log() {
    local -r user="$(id -nu "$(< "/proc/self/loginuid")" 2>/dev/null || true)"
    local tag; tag="$(basename "${0}")"

    [[ "${1}" =~ ^([A-Za-z]*):\ *(.*) ]] && {
       local -r priority=${BASH_REMATCH[1]}
       local message="${FUNCNAME[1]}(): ${BASH_REMATCH[2]}"; }

    [ "${FAKE:-}" == "true" ] && message="FAKE-Mode: ${message}"
    message="${user:-${USER}}: ${priority}: '${message}'"

    [ "${LOG_STDOUT:-"true"}" == "true" ] &&
        echo "$(date '+%b %e %H:%M:%S') $(hostname -s
                ) ${tag}}[${$}]: ${message}"

    [[ "${SYSLOG:-}" == "true" || "${2:-}" == "force" ]] &&
        logger --id="${$}" -t "${tag}" -p "syslog.${priority,,}" "${message}"

    return 0
}


###############################################################################
#
#   Name       : _ping_range
#   Parameters : $1 : The network interface that is being worked on.
#              : $2 : The network interface IP address.
#              : $3 : IP addresses found for all network interfaces.
#   Globals    : $PINTLIST       : A file reference of IPs to be checked
#                                  (expert setting).
#              : $RANGE          : Details of IPs to be checked.
#              : $PINGLIST_IFACE : Associative array for storing network
#                                  interface IP addresses.
#   Return     : Number of active IP on network interfaces.
#
_ping_range() {
    local -r net_iface="${1}"
    local -r server_ip="${2}"
    local -r server_ips="${3// /\\|}"

    local ip_list=()
    local pinglist_array=()
    local -r empty="No IP addresses specified"

    [ "${DEBUG}" == "true" ] && {
        _log "DEBUG: INTERFACE: ${net_iface}"
        _log "DEBUG: CLASS: ${server_ip%.*}"
        _log "DEBUG: PINGLIST: ${PINGLIST:-N/A}"
        _log "DEBUG: RANGE: ${RANGE:-N/A}"; }

    local key="${PINGLIST:-"${net_iface}"}"
    if [ -z "${PINGLIST_IFACE["${key}"]:-}" ]; then
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Generating new PINGLIST_IFACE[${key}]"

        if [ -n "${PINGLIST:-}" ]; then
            mapfile -t ip_list < "${PINGLIST}"
        else
            for rg in ${RANGE//,/ }; do
                if [[ "${rg}" =~ ^([a-z]+[0-9]+)[:] &&
                        "${BASH_REMATCH[1]}" != "${net_iface}" ]]; then
                    continue
                elif [[ "${rg}" =~ ^([a-z]+[0-9]+[:])?(([0-9]{1,3}\.){3})?([1-9][0-9]{0,2})$ ]]; then
                    mapfile -t -O "${#ip_list[@]}" ip_list <<< \
                        "${BASH_REMATCH[2]:-"${server_ip%.*}."}${BASH_REMATCH[4]}"
                elif [[ "${rg}" =~ ^([a-z]+[0-9]+[:])?(([0-9]{1,3}\.){3})?([1-9][0-9]{0,2})\.{2}([1-9][0-9]{0,2})$ ]]; then
                    local min="${BASH_REMATCH[4]}" max="${BASH_REMATCH[5]}"
                    [ "${BASH_REMATCH[5]}" -lt "${BASH_REMATCH[4]}" ] && {
                        min="${BASH_REMATCH[5]}"; max="${BASH_REMATCH[4]}"; }
                    mapfile -t -O "${#ip_list[@]}" ip_list < <(
                        seq -f "${BASH_REMATCH[2]:-"${server_ip%.*}."}%g" \
                            "${min}" "${max}")
                elif [[ "${rg}" =~ ^([a-z]+[0-9]+[:])?(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])))$ ]]; then
                    mapfile -t -O "${#ip_list[@]}" ip_list <<< \
                        "${BASH_REMATCH[2]}"
                fi
            done
        fi
        PINGLIST_IFACE["${key}"]="$(
            printf '%s\n' "${ip_list[@]}" |
            sort -t . -k 3,3n -k 4,4n | uniq |
            grep -v "${server_ips}")"
    fi
    mapfile -t pinglist_array <<< "${PINGLIST_IFACE["${key}"]:-${empty}}"

    [ "${DEBUG}" == "true" ] &&
        _log "DEBUG: pinglist_array: ${pinglist_array[*]:-"${empty}"}"

    [[ "${pinglist_array[0]}" == "${empty}" ]] && {
        _log "INFO: No IP addresses specified for: ${net_iface} -> next check"
        return 0; }

    _log "INFO: Retrieve list of active IPs for: ${net_iface}"
    local -r fping_result="$(LC_ALL=C
        fping --iface="${net_iface}" --quiet --alive --retry=1 \
              --addr "${pinglist_array[@]}" |
        grep -v "${server_ips}" || true)"

    [ -z "${fping_result}" ] && {
        _log "INFO: No active IPs found in the specified range -> next check"
        return 0; }

    local active_ip; while read -r active_ip; do
        _log "INFO: ${active_ip} is active"
    done < <(sort -t . -k 3,3n -k 4,4n <<< "${fping_result}")

    _log "INFO: Active IPs found in the specified range -> no shutdown"
    return "$(wc -l <<< "${fping_result}")"
}


###############################################################################
#
#   Name       : _shutdown
#   Parameters : None
#   Globals    : $SHUTDOWNCOMMAND : The shutdown command to use as defined by
#                                   the configuration option.
#              : $FAKE            : Are we in fake mode and hence do not
#                                   not real shutdown command just stop.
#   Return     : None, script exit point.
#
# We've had no responses for the required number of consecutive scans defined in
# $CYCLES shutdown and power off.
#
_shutdown() {
    # When FAKE-Mode is on.
    [ "${FAKE}" == "true" ] && {
        _log "INFO: Fake-shutdown issued: '${SHUTDOWNCOMMAND}' - Command is not executed because of Fake-Mode" force
        _log "INFO: Autoshutdown will end here"
        exit 0; }

    # Without Fake-Mode.
    _log "INFO: Shutdown issued: '${SHUTDOWNCOMMAND}'" force
    # Write everything to disk/stick and shutdown, hibernate, ....
    sync && eval "${SHUTDOWNCOMMAND}" && exit 0
    # Sleep 5 minutes to allow the /etc/init.d/autoshutdown to kill the script
    # and give the right log-message. If we exit here immediately, there are
    # errors in the log.
    sleep 5m
    # We need this just for debugging - the system should be shutdown here.
    _log "INFO: 5 minutes are over" force
    sleep 5m
    _log "INFO: Another 5 minutes are over" force
    exit 1
}


###############################################################################
#
#   Name       : _check_processes
#   Parameters : None
#   Globals    : $LOADPROCNAMES : Command names of processes with load
#                                 dependent children.
#              : $TEMPPROCNAMES : Command names of processes only started when
#                                 active.
#   Return     : 0         : If no active process has been found.
#              : 1 or more : If at least one active process has been found.
#
_check_processes() {
    # Check for each given command name in LOADPROCNAMES if it is currently
    # stated active in "top". It has been found, that smbd, proftpd, nsfd,
    # ... There are processes always present in "ps" or "top" output (This
    # could be due to the "daemon" mechanism.) So the only chance to identify
    # there is something happening with these processes, is to check if "top"
    # states them active hence the "-i" parameter is required.
    local num_load_proc=0
    for process in ${LOADPROCNAMES//,/ }; do
        local lp=0
        local l_proc=0
        for (( N=0; N < LPREPEAT; N++ )); do
            local lp_result; lp_result="$(LC_ALL=C
                top -i -b -d 1 -n 1 |
                awk -v regex="^${process}$" -v count=0 \
                    '$NF ~ regex {count++} END{print count}')"
            lp=$((lp | lp_result))
            l_proc=$((l_proc + lp_result))
        done
        num_load_proc=$((num_load_proc + lp))
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Load processes: ${process}: Found ${l_proc} active after ${LPREPEAT} cycles"
    done
    [ "${num_load_proc}" -gt 0 ] &&
        _log "INFO: Found ${num_load_proc} active from: ${LOADPROCNAMES}"

    # Check for each given command name in TEMPPROCNAMES if it is currently
    # stated present in "top". It is not guaranteed, that top states these
    # services active, as they usually wait for user input, so no "-i"
    # parameter on the command line, but shear presence of the process is
    # enough.
    local num_temp_proc=0
    for process in ${TEMPPROCNAMES//,/ }; do
        local tp=0
        local t_proc=0
        for (( N=0; N < TPREPEAT; N++ )); do
            local tp_result; tp_result="$(LC_ALL=C
                top -b -d 1 -n 1 |
                awk -v regex="^${process}$" -v count=0 \
                    '$NF ~ regex {count++} END{print count}')"
            # If there is no process with top, try "pgrep", but not in.tftpd.
            [ "${tp_result}" -eq 0 ] &&
                if [ "${process}" != "in.tftpd" ]; then
                    tp_result="$(LC_ALL=C pgrep -fc "${process}")"
                else
                    [ "${DEBUG}" == "true" ] && {
                        _log "DEBUG: Temp processes: Skipping 'in.tftpd'"
                        break; }
                fi
            tp=$((tp | tp_result))
            t_proc=$((t_proc + tp_result))
        done
        num_temp_proc=$((num_temp_proc + tp))
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Temp processes: ${process}: Found ${t_proc} active after ${TPREPEAT} cycles"
    done
    [ "${num_temp_proc}" -gt 0 ] &&
        _log "INFO: Found ${num_temp_proc} active from: ${TEMPPROCNAMES}"

    local active=$(( num_load_proc + num_temp_proc ))
    local msg="INFO: Found ${active} process(es) active -> "
    if [ "${active}" -eq 0 ]; then
        _log "${msg}next check"
    else
        _log "${msg}no shutdown"
    fi
    return "${active}"
}


###############################################################################
#
#   Name       : _check_plugin
#   Parameters : None
#   Globals    : None
#   Return     : 0 : If file has not been found.
#              : 1 : If file has been found.
#
# With this plugin-system we can check if a specific file exists. If it exists,
# the machine won't shutdown. You find sample plugins in: /etc/autoshutdown.d
#
_check_plugin() {
    local foundvalue=0
    for plugin in /etc/autoshutdown.d/*; do
        [ ! -f "${plugin}" ] && {
            [ "${DEBUG}" == "true" ] &&
                _log "DEBUG: Ignoring: ${plugin} as is it not a plugin file"
            continue; }

        local name="${plugin##*/}"
        [ "${DEBUG}" == "true" ] && {
            _log "DEBUG: -----------------------------------------------------"
            _log "DEBUG: ${name}: plugin: ${plugin}"; }

        for var in "enabled:true" "folder:N/A" "file:N/A" "content:N/A"; do
            local value="${var%:*}"
            declare "${value}"="$(
                awk -F= -v regex="${var%:*}=" \
                    '$0 ~ regex {gsub(/["]/,"",$2);print $2}' "${plugin}")"
             [ "${DEBUG}" == "true" ] &&
                _log "DEBUG: ${name}: ${value}: ${!value:-"${var#*:}"}"
        done

        # shellcheck disable=SC2154
        [ "${enabled}" == "false" ] && {
            _log "INFO: ${name}: Plugin is disabled skipping -> next check"
            continue; }

        # shellcheck disable=SC2154
        [ -z "$(find "${folder}" -regextype posix-egrep \
                    -regex ".*${file}" 2>/dev/null)" ] && {
            _log "INFO: ${name}: File not found -> next check"
            continue; }

        # shellcheck disable=SC2154
        if [ -z "${content}" ]; then
            _log "INFO: ${name}: File found -> no shutdown"
            (( foundvalue+=1 ))
        elif grep -q "${content}" "${folder}/${file}"; then
            _log "INFO: ${name}: Content found (${content}) -> no shutdown"
            (( foundvalue+=1 ))
        else
            _log "INFO: ${name}: Content not found (${content}) -> next check"
        fi
    done

    [ "${DEBUG}" == "true" ] && {
        _log "DEBUG: -----------------------------------------------------"
        _log "DEBUG: All plugins processed: Active plugins: ${foundvalue}"; }

    [ "${foundvalue}" -gt 0 ] && return 1
    return 0
}


###############################################################################
#
#   Name       : _check_loadaverage
#   Parameters : None
#   Globals    : $LOADAVERAGE : Integer load average.
#   Return     : 1 : If load average is higher (greater) than LOADAVERAGE, no
#                    shutdown.
#              : 0 : If load average is lower (less) than LOADAVERAGE.
#
# Checks if the load average is higher than LOADAVERAGE over the last 1 minute.
# If yes -> no shutdown, next cycle. If no  -> next check and shutdown if all
# cycles failed.
#
_check_loadaverage() {
    # Get the load averages.
    local -r loadavg_line="$(< "/proc/loadavg")"
    # Get load average in decimal notation.
    local -r loadavg_dec="$(awk '{print $1}' <<< "${loadavg_line}")"
    # Convert to integer value by removing decimal point and assuming two fixed
    # decimal places.
    local -r loadavg="$(sed 's/[.]//;s/^0*//g;s/^$/0/' <<< "${loadavg_dec}")"

    [ "${DEBUG}" == "true" ] && {
        _log "DEBUG: -----------------------------------------------------"
        _log "DEBUG: Output from '/proc/loadavg': ${loadavg_line}"
        _log "DEBUG: load average decimal: ${loadavg_dec}"
        _log "DEBUG: load average: ${loadavg}"; }

    local msg="INFO: Load average (${loadavg_dec} -> ${loadavg}) is"
    [ "${loadavg}" -gt "${LOADAVERAGE}" ] && {
        _log "${msg} higher than target (${LOADAVERAGE}) -> no shutdown"
        return 1; }

    _log "${msg} lower than target (${LOADAVERAGE}) -> next check"
    return 0
}


###############################################################################
#
#   Name       : _check_net_status
#   Parameters : $1 : Network interface under test.
#              : $2 : The network interface IP address.
#   Globals    : $NSOCKETNUMBERS    : Socket number to check for activity.
#              : $NSOCKETIGNORESELF : If set will ignore the network interface
#                                     IP address as a connection.
#   Return     : 0         : If no active socket has been found, shutdown.
#              : 1 or more : If at least one active socket has been found, no
#                            shutdown.
#
_check_net_status() {
    local -r net_iface="${1}"
    local -r server_ip="${2}"

    local active=0
    local -r empty="Found no active connections"

    _log "INFO: Check connections for: ${net_iface}"

    # Check for each given socket number in NSOCKETNUMBERS to see if it is
    # currently stated active by the ss command.
    for nsocket in ${NSOCKETNUMBERS//,/ }; do
        local lines; lines="$(LC_ALL=C
            ss -n |
            awk -v regex="^([[]::ffff:)?${server_ip}[]]?:${nsocket}$" \
                -v ignore_self="${NSOCKETIGNORESELF}" \
                -v server_ip="${server_ip}" \
                "(ignore_self == \"false\") ? \
                    \$2 ~ /^ESTAB$/ && \$5 ~ regex : \
                    \$2 ~ /^ESTAB$/ && \$5 ~ regex && \$6 !~ server_ip")"

        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Port ${nsocket}: ${lines:-"${empty}"}"

        # No active connection found.
        [ -z "${lines}" ] && continue

        local no_lines; no_lines="$(wc -l <<< "${lines}")"
        (( active+="${no_lines}" ))

        local conips; conips="$(
            awk '{gsub(/^([[]::ffff:)?/,"",$6);
                  gsub(/[]]?:[0-9]+$/,"",$6); print $6}' <<< "${lines}" |
            sort -t . -k 3,3n -k 4,4n | uniq)"

        # Set portprotocol - Only default ports are defined here.
        local portprotocol
        case "${nsocket}" in
            80|8080) portprotocol="HTTP" ;;
            22)      portprotocol="SSH" ;;
            21)      portprotocol="FTP" ;;
            139|445) portprotocol="SMB/CIFS" ;;
            443)     portprotocol="HTTPS" ;;
            548)     portprotocol="AFP" ;;
            873)     portprotocol="RSYNC" ;;
            3306)    portprotocol="MYSQL" ;;
            3689)    portprotocol="DAAP" ;;
            6991)    portprotocol="BITTORRENT" ;;
            9091)    portprotocol="BITTORRENT_WEBIF" ;;
            32400)   portprotocol="PLEXMEDIASERVER" ;;
            49152)   portprotocol="UPNP" ;;
            51413)   portprotocol="BITTORRENT" ;;
            *)       portprotocol="unknown" ;;
        esac

        _log "INFO: Found ${no_lines} active connection on port ${nsocket} (${portprotocol}) from: ${conips//$'\n'/, }"
    done

    _log "INFO: Found ${active} active socket(s) on ${net_iface}, from port(s): ${NSOCKETNUMBERS}"

    # Return the number of active sockets found.
    return "${active}"
}


###############################################################################
#
#   Name       : _check_docker_status
#   Parameters : None
#   Globals    : $NSOCKETNUMBERS : Socket number to check for activity.
#   Return     : 0         : If no active socket has been found, shutdown.
#              : 1 or more : If at least one active socket has been found,
#                            no shutdown.
#
_check_docker_status() {
    command -v docker &>/dev/null || return 0
    local active=0
    for container in $(docker ps --format "{{ .Names }}"); do
        local info; read -ra info <<< "$(LC_ALL=C docker inspect --format \
            '{{ .State.Pid }} {{ .NetworkSettings.IPAddress }}
             {{- ""}} {{ range $key, $value := .NetworkSettings.Ports }}
                {{- ""}}{{ range . }}{{ .HostPort }}:{{ index (split $key "/") 0 }}
                {{- ""}}{{ end }}
             {{- ""}} {{ end }}' \
            "${container}")"
        [[ "${#info[@]}" -eq 0 || ! ("${info[*]}" =~ :) ]] && continue
        local p_map=()
        local nsocketnums
        mapfile -t nsocketnums <<< "${NSOCKETNUMBERS//,/$'\n'}"
        for ports in "${info[@]: -2}"; do
            [[ "${ports}" =~ (.*)-(.*):(.*)-(.*) ]] && {
                local h_map; mapfile -t h_map < <(
                    seq "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}")
                local c_map; mapfile -t c_map < <(
                    seq "${BASH_REMATCH[3]}" "${BASH_REMATCH[4]}")
                for index in "${!h_map[@]}"; do
                    [[ " ${nsocketnums[*]} " =~ \ ${h_map["${index}"]}\  ]] &&
                        p_map["${h_map["${index}"]}"]="${c_map["${index}"]}"
                done
                continue; }
            [[ " ${nsocketnums[*]} " =~ \ ${ports%:*}\  ]] &&
                p_map["${ports%:*}"]="${ports#*:}"
        done
        [ "${#p_map[@]}" -eq 0 ] && continue
        for target in "${!p_map[@]}"; do
            local lines; lines="$(LC_ALL=C
                nsenter -t "${info[0]}" -n ss -n |
                awk -v \
                    regex="^([[]::ffff:)?${info[1]}[]]?:${p_map[${target}]}$" \
                    '$2 ~ /^ESTAB$/ && $5 ~ regex' ||
                true)"
            local con_ips; con_ips="$(
                awk '{gsub(/^([[]::ffff:)?/,"",$6);
                      gsub(/[]]?:[0-9]+$/,"",$6);
                      print $6}' <<< "${lines}" |
                sort -t . -k 3,3n -k 4,4n | uniq)"
            [ -n "${lines}" ] &&
                { local no_lines; no_lines="$(wc -l <<< "${lines}")"
                  (( active+="${no_lines}" ))
                  _log "INFO: Found ${no_lines} active connection on port ${target} (${container}) from: ${con_ips//$'\n'/, }"; }
        done
    done
    _log "INFO: Found ${active} active socket(s), from port(s): ${NSOCKETNUMBERS}"
    return "${active}"
}


###############################################################################
#
#   Name       : _check_users_cli_status
#   Parameters : None
#   Globals    : None
#   Return     : 0 : If there are no connected users, ready for shutdown.
#              : 1 : If there are connected users, no shutdown.
#
_check_users_cli_status() {
    local -r users_connected="$(LC_ALL=C w -hs)"

    [ -z "${users_connected}" ] && {
        _log "INFO: There are no users connected -> next check"
        return 0; }

    [ "${DEBUG}" == "true" ] && {
        _log "DEBUG: Connected users:"
        local user; while read -r user; do
            _log "DEBUG: ${user}"
        done <<< "${users_connected}"; }

    local connecton; while read -r connecton; do
        local connected_user; connected_user="$(
            awk '{print $1}' <<< "${connecton}")"
        local connecton_from; connecton_from="$(
            awk '{gsub(/^-$/,"localhost",$3);
                  print $2 " " $3}' <<< "${connecton}" )"
        _log "INFO: User: ${connected_user} on from ${connecton_from}"
    done <<< "${users_connected}"

    _log "INFO: There are users connected -> no shutdown"
    return 1
}


###############################################################################
#
#   Name       : _check_smb_status
#   Parameters : None
#   Globals    : None
#   Return     : 0 : If there are no smb client connected, ready for shutdown.
#              : 1 : If there are smb client connected, no shutdown.
#
_check_smb_status() {
    local -r smb_conns="$(LC_ALL=C smbstatus --brief | awk 'NR>4')"
    local smb_lock_pids; mapfile -t smb_lock_pids <<< "$(LC_ALL=C
        smbstatus --locks | awk '$1 ~ /[0-9]+/{print $1}' | sort -u)"

    [[ -z "${smb_conns}" || ! "${smb_lock_pids[*]}" ]] && {
        _log "INFO: No SMB clients connected with locks -> next check"
        return 0; }

    _log "INFO: SMB client(s) with locks:"
    local pid user host prot; while read -r pid user host prot; do
        [[ " ${smb_lock_pids[*]} " =~ \ ${pid}\  ]] &&
            _log "INFO: HOST: ${host} PID: ${pid} USER: ${user} PROTO: ${prot}"
    done < <(awk '{print $1 " " $2":"$3 " " $4 " " $6}' <<< "${smb_conns}")

    _log "INFO: SMB clients with locks connected -> no shutdown"
    return 1
}


###############################################################################
#
#   Name       : _check_ul_dl_rate
#   Parameters : $1 : The network interface to check.
#   Globals    : $ULDLRATE     : Rate in kB/s of network activity.
#              : $P_UL_DL_RATE : Associative array for strong a network
#                                interface tx, rx and epoch values.
#   Return     : 0 : If not enough network activity, ready for shutdown.
#              : 1 : If enough network activity, no shutdown.
#
_check_ul_dl_rate() {
    local -r net_iface="${1}"

    _log "INFO: Running on interface: ${net_iface}"

    local -r epoch_sec="${EPOCHSECONDS}"
    local -r last_checked_sec=$((
        epoch_sec - ${P_UL_DL_RATE["${net_iface}_epoch_sec"]:-${epoch_sec}}))

    local -r rx_kb="$(awk '{printf("%.0f",($0/1024))}' \
                "/sys/class/net/${net_iface}/statistics/rx_bytes")"
    local -r tx_kb="$(awk '{printf("%.0f",($0/1024))}' \
                "/sys/class/net/${net_iface}/statistics/tx_bytes")"

    [ "${DEBUG}" == "true" ] &&
        _log "DEBUG: Actual: TX kB: ${tx_kb}, RX kB: ${rx_kb}"

    [[ "${last_checked_sec}" -eq 0 ||
          -z "${P_UL_DL_RATE["${net_iface}_epoch_sec"]:-}" ||
          -z "${P_UL_DL_RATE["${net_iface}_tx"]:-}" ||
          -z "${P_UL_DL_RATE["${net_iface}_rx"]:-}" ]] && {
        # Store current value.
        P_UL_DL_RATE["${net_iface}_epoch_sec"]="${epoch_sec}"
        P_UL_DL_RATE["${net_iface}_rx"]="${rx_kb}"
        P_UL_DL_RATE["${net_iface}_tx"]="${tx_kb}"

        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Store new TX, RX and epoch values"
        return 0; }

    [ "${DEBUG}" == "true" ] &&
        _log "DEBUG: Previous TX kB: ${P_UL_DL_RATE["${net_iface}_tx"]}, RX kB: ${P_UL_DL_RATE["${net_iface}_rx"]}"

    # Calculate threshold limit (defined kB/s multiplied with second since
    # last checked) to get the total value of kB over the 'last checked
    # time' - 'time now'.
    local ul_dl_increase=$((ULDLRATE * last_checked_sec))

    # Calculate the total value.
    local t_rx=$((P_UL_DL_RATE["${net_iface}_rx"] + ul_dl_increase))
    local t_tx=$((P_UL_DL_RATE["${net_iface}_tx"] + ul_dl_increase))

    # Calculate difference between the last and the actual value.
    local diff_rx=$((rx_kb - P_UL_DL_RATE["${net_iface}_rx"]))
    local diff_tx=$((tx_kb - P_UL_DL_RATE["${net_iface}_tx"]))

    # Calculate dl/ul-rate in kB/s - format xx.x.
    local last_dl_rate; last_dl_rate=$(
        awk '{printf("%.1f",($1/$2))}' <<< "${diff_rx} ${last_checked_sec}")
    local last_ul_rate; last_ul_rate=$(
        awk '{printf("%.1f",($1/$2))}' <<< "${diff_tx} ${last_checked_sec}")

    [ "${DEBUG}" == "true" ] && {
        _log "DEBUG: last_checked_sec ${last_checked_sec}"
        _log "DEBUG: ul_dl_increase: ${ul_dl_increase}"
        _log "DEBUG: t_rx: ${t_rx}"
        _log "DEBUG: diff_rx: ${diff_rx}"
        _log "DEBUG: t_tx: ${t_tx}"
        _log "DEBUG: diff_tx: ${diff_tx}"
        _log "DEBUG: Check: rx_kb:${rx_kb} <= t_rx:${t_rx}"
        _log "DEBUG: Check: tx_kb:${tx_kb} <= t_tx:${t_tx}"; }

    # Store current value.
    P_UL_DL_RATE["${net_iface}_epoch_sec"]="${epoch_sec}"
    P_UL_DL_RATE["${net_iface}_rx"]="${rx_kb}"
    P_UL_DL_RATE["${net_iface}_tx"]="${tx_kb}"

    local msg="INFO: Network interface: ${net_iface} (last ${last_checked_sec}s) "
          msg+="DL: ${last_dl_rate} kB/s, UL: ${last_ul_rate} kB/s"

    [[ "${rx_kb}" -gt "${t_rx}" || "${tx_kb}" -gt "${t_tx}" ]] && {
        _log "${msg} over ${ULDLRATE} kB/s -> no shutdown"
        return 1; }

    _log "${msg} under ${ULDLRATE} kB/s -> next check"
    return 0
}


###############################################################################
#
#   Name       : _check_clock
#   Parameters : None
#   Globals    : $UPHOURS         : Range of hours, where system should go to
#                                   sleep. e.g. 06:00..20:00.
#              : $OVERRIDEUPHOURS : Range of hours overriding default UPHOURS
#                                   for days of the week. e.g.
#                                   Sat:00:00..23:59,Sun:00:00..21:59
#   Return     : 0 : If actual value of hours is in DOWN range, ready for
#                    shutdown.
#              : 1 : If actual value of hours is in UP range, sleep till DOWN
#                    range, block shutdown.
#
_check_clock() {
    local -r epoch_sec="${EPOCHSECONDS}"
    local -r current_time="$(date -d @"${epoch_sec}" +%R)"

    local -r overide_uphours="${OVERRIDEUPHOURS:-}"
    local up_hours="${UPHOURS}"
    for override in ${overide_uphours//,/ }; do
        local o_hours="${override#*:}"
        local o_start; o_start="$(date -f - "+%R" <<< "${o_hours%..*}")"
        local o_end; o_end="$(date -f - "+%R" <<< "${o_hours#*..}")"
        [[ "$(date "+%a")" == "${override%%:*}" ||
           ("$(date "+%a" -d "1 day ago")" == "${override%%:*}" &&
            "${o_start}" > "${o_end}" &&
            ( "${current_time}" < "${o_end}" ||
              "${current_time}" == "${o_end}" )) ]] && {
                up_hours="${o_hours}"
                _log "INFO: OVERRIDEUPHOURS found applying: ${override}"
                break; }
    done

    local -r range_start="$(date -f - "+%R" <<< "${up_hours%..*}")"
    local -r range_end="$(date -f - "+%R" <<< "${up_hours#*..}")"

    local epoch_start; epoch_start="$(date -f - +%s <<< \
            "$(date -d @"$((epoch_sec))" +%D) ${range_start}")"
    local epoch_end; epoch_end="$(date -f - +%s <<< \
            "$(date -d @"$((epoch_sec))" +%D) ${range_end}")"
    # Fix epoch if we are wrapped around midnight applying a lexicographic
    # comparison.
    [[ "${range_start}" > "${range_end}" ]] &&
        if [[ "${current_time}" > "${range_start}" ||
              "${current_time}" == "${range_start}" ||
              "${current_time}" > "${range_end}" ||
              "${current_time}" == "${range_end}" ]]; then
            epoch_end="$(date -f - +%s <<< \
                "$(date -d @"$((epoch_sec + 86400))" +%D) ${range_end}")"
        else
            epoch_start="$(date -f - +%s <<< \
                "$(date -d @"$((epoch_sec - 86400))" +%D) ${range_start}")"
        fi

    # If it negative or zero we already in the shutdown window.
    local seconds_to_sleep="$((epoch_end - epoch_sec))"
    local msg; msg="DEBUG: Current time: $(date -d @"${epoch_sec}"), "
          msg+="Stay up range - start: ${range_start}, end: ${range_end} -> "
    [[ "${epoch_sec}" -lt "${epoch_start}" ||
          "${epoch_sec}" -ge "${epoch_end}" ||
          "${seconds_to_sleep}" -le 0 ]] && {
        [ "${DEBUG}" == "true" ] && _log "${msg}allow shutdown"
       _log "INFO: System is in shutdown range -> next check"
       return 0; }

    [ "${DEBUG}" == "true" ] && _log "${msg}stay up"
    _log "INFO: System is in stay up range"
    _log "INFO: Sleeping until: $(
            date -d @"$((epoch_sec + seconds_to_sleep))"
                ) -> ${seconds_to_sleep}s"
    sleep "${seconds_to_sleep}"
    return 1
}


###############################################################################
#
#   Name       : _check_hddio
#   Parameters : None
#   Globals    : $HDDIO_RATE   : Rate in kB/s of HDD-IO.
#              : $P_HDDIO_DEVS : Associative array for storing read, wrtn and
#                                epoch values.
#   Return     : 0 : If actual value of hddio is lower than the defined value,
#                    ready for shutdown.
#              : 1 : If actual value of hddio is higher than the defined value,
#                    no shutdown.
#
_check_hddio() {
    local rvalue=0

    [ "${DEBUG}" == "true" ] &&
        _log "DEBUG: HDDIO_RATE: ${HDDIO_RATE} kB/s"

    local -r epoch_sec="${EPOCHSECONDS}"
    local -r last_checked_sec=$((
        epoch_sec - ${P_HDDIO_DEVS["epoch_sec"]:-${epoch_sec}}))

    local hdd hdd_in hdd_out; while read -r hdd hdd_in hdd_out; do
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: ========== Device: ${hdd} =========="

        ! mount -l | grep -q "${hdd}" && {
            [ "${DEBUG}" == "true" ] &&
                _log "DEBUG: Skipping as no mount point"
            continue; }

        [ "${DEBUG}" == "true" ] && {
            local line; while read -r line; do
                _log "DEBUG: ${line}"
            done < <(blkid -s LABEL -s UUID | grep "${hdd}")
            _log "DEBUG: Actual: kB_read: ${hdd_in}, kB_wrtn: ${hdd_out}"; }

        [[ "${rvalue}" -eq 1 || "${last_checked_sec}" -eq 0 ||
              -z "${P_HDDIO_DEVS["epoch_sec"]:-}" ||
              -z "${P_HDDIO_DEVS["${hdd}_r"]:-}" ||
              -z "${P_HDDIO_DEVS["${hdd}_w"]:-}" ]] && {
            # Store current value.
            P_HDDIO_DEVS["${hdd}_r"]="${hdd_in}"
            P_HDDIO_DEVS["${hdd}_w"]="${hdd_out}"

            [ "${DEBUG}" == "true" ] &&
                _log "DEBUG: Store new read/write value for device"
            continue; }

        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Previous: kB_read: ${P_HDDIO_DEVS["${hdd}_r"]}, kB_wrtn: ${P_HDDIO_DEVS["${hdd}_w"]}"

        # Calculate threshold limit (defined kB/s multiplied with second since
        # last checked) to get the total value of kB over the 'last checked
        # time' - 'time now'.
        local hddio_increase=$((HDDIO_RATE * last_checked_sec))

        # Calculate the total value.
        local t_hddio_read=$((P_HDDIO_DEVS["${hdd}_r"] + hddio_increase))
        local t_hddio_write=$((P_HDDIO_DEVS["${hdd}_w"] + hddio_increase))

        # Calculate difference between the last and the actual value.
        local diff_hddio_read=$((hdd_in - P_HDDIO_DEVS["${hdd}_r"]))
        local diff_hddio_write=$((hdd_out - P_HDDIO_DEVS["${hdd}_w"]))

        # Calculate hddio-rate in kB/s - format xx.x.
        local last_hddio_read_rate; last_hddio_read_rate="$(
            awk '{printf("%.1f",($1/$2))}' <<< \
                 "${diff_hddio_read} ${last_checked_sec}")"
        local last_hddio_write_rate; last_hddio_write_rate="$(
            awk '{printf("%.1f",($1/$2))}' <<< \
                 "${diff_hddio_write} ${last_checked_sec}")"

        [ "${DEBUG}" == "true" ] && {
            _log "DEBUG: last_checked_sec: ${last_checked_sec}"
            _log "DEBUG: hddio_increase: ${hddio_increase}"
            _log "DEBUG: t_hddio_read: ${t_hddio_read}"
            _log "DEBUG: diff_hddio_read: ${diff_hddio_read}"
            _log "DEBUG: t_hddio_write: ${t_hddio_write}"
            _log "DEBUG: diff_hddio_write: ${diff_hddio_write}"
            _log "DEBUG: Check: 'hdd_in: ${hdd_in}' <= 't_hddio_read: ${t_hddio_read}'"
            _log "DEBUG: Check: 'hdd_out: ${hdd_out}' <= 't_hddio_write: ${t_hddio_write}'"; }

        # Store current value.
        P_HDDIO_DEVS["${hdd}_r"]="${hdd_in}"
        P_HDDIO_DEVS["${hdd}_w"]="${hdd_out}"

        local msg="INFO: Device: ${hdd} (last ${last_checked_sec}s) "
              msg+="kB_read/s: ${last_hddio_read_rate}, "
              msg+="kB_wrtn/s: ${last_hddio_write_rate}"

        if [[ "${hdd_in}" -gt "${t_hddio_read}" ||
              "${hdd_out}" -gt "${t_hddio_write}" ]]; then
            _log "${msg} over: ${HDDIO_RATE} kB/s -> no shutdown"
            rvalue=1
        else
            _log "${msg} under: ${HDDIO_RATE} kB/s -> next check"
        fi

    done < <(LC_ALL=C iostat -kdyNz |
             awk 'NR>3 && !/^$/{print $1 " " $5 " " $6}')

    P_HDDIO_DEVS["epoch_sec"]="${epoch_sec}"

    [ "${DEBUG}" == "true" ] && _log "DEBUG: rvalue: ${rvalue}"

    _log "INFO: All checks complete"
    return "${rvalue}"
}


###############################################################################
#
#   Name       : _check_smart
#   Parameters : None
#   Globals    : None
#   Return     : 1 : If any HDD is running smart tests then no shutdown.
#              : 0 : If no HDD is running smart tests.
#
# This checks if a device is running smart tests, if S.M.A.R.T is supported
# directly by the device and its controller. For example this will not work on
# a HPE smart array. If smart tests are running on a supported device then
# no shutdown. If no smart tests or device/controller is not supported go to
# next check.
#
_check_smart() {
    for hdd in /dev/sd[a-z]; do
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Checking device for running smart tests: ${hdd}"

        local smart_output; smart_output="$(LC_ALL=C
            smartctl --all --nocheck=standby "${hdd}" || true)"

        [ "${DEBUG}" == "true" ] && {
            _log "DEBUG: Smartctl output: ${hdd}"
            local line; while read -r line; do
               _log "DEBUG: ${line}"
            done <<< "${smart_output}"; }

        grep -q "in[ _]progress" <<< "${smart_output}" && {
            _log "INFO: Device ${hdd} is runs a SMART tests -> no shutdown"
            return 1; }
    done

    _log "INFO: No supported device is running SMART tests -> next check"
    return 0
}


###############################################################################
#
#   Name       : _check_config
#   Parameters : None
#   Globals    : $CONFIG    : The autoshutdown configuration.
#              : $*         : All options as defined in $CONFIG for validation.
#              : $DEFAULT_* : All options as defined in $DEFAULT_CONFIG for
#                             default value reset in case of error.
#   Return     : 0 on success.
#
_check_config() {
    _log "INFO: ------------------------------------------------------"
    _log "INFO: Checking config: ${CONFIG}"

    [[ "${FAKE}" == "true" || "${FAKE}" == "false" ]] || {
        _log "WARNING: FAKE not set properly: ${FAKE}"
        _log "WARNING: FAKE has to be set to 'true' or 'false'"
        _log "WARNING: Set FAKE to true -> Test-mode with VERBOSE true"
        FAKE="true"; VERBOSE="true"; DEBUG="true"; }

    [[ "${ENABLE}" == "true" || "${ENABLE}" == "false" ]] || {
        _log "WARNING: ENABLE not set properly: ${ENABLE}"
        _log "WARNING: ENABLE has to be set to 'true' or 'false'"
        _log "ERR: Exiting ..."
        exit 1; }

    # Flag: 1 - 999 (cycles).
    [[ "${CYCLES}" =~ ^([1-9]|[1-9][0-9]|[1-9][0-9]{2})$ ]] || {
        _log "WARNING: Invalid parameter format: Flag"
        _log "WARNING: You set it to '${CYCLES}', which is not the correct syntax. Only '1' - '999' is allowed"
        _log "WARNING: Setting CYCLES to default: ${DEFAULT_CYCLES}"
        CYCLES="${DEFAULT_CYCLES}"; }

    # Validate *CHECK* variables.
    local var; while read -r var; do
        local default_var="DEFAULT_${var}"
        [[ "${!var}" == "true" || "${!var}" == "false" ]] || {
            _log "WARNING: ${var} not set properly: ${!var}"
            _log "WARNING: ${var} has to be set to 'true' or 'false'"
            _log "WARNING: ${var} set to default: ${!default_var}"
            declare -g "${var}"="${!default_var}"; }
    done < <(awk -F= '$0 !~ /^#/ && /.*CHECK.*/{print $1}' "${CONFIG}")

    if [ "${CHECKCLOCKACTIVE}" == "true" ]; then
        [[ "${UPHOURS}" =~ ^((([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?)).{2}(([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?)))$ &&
           "${BASH_REMATCH[2]}" != "${BASH_REMATCH[6]}" ]] || {
            _log "WARNING: Invalid parameter list format: UPHOURS [hour1..hour2] and hour1 != hour2"
            _log "WARNING: You set it to '${UPHOURS}', which is not the correct syntax. Maybe it's empty?"
            _log "WARNING: Setting UPHOURS to default: ${DEFAULT_UPHOURS}"
            UPHOURS="${DEFAULT_UPHOURS}"; }

        if [ -n "${OVERRIDEUPHOURS:-}" ]; then
           local -r short_days="$(locale abday | sed 's:;:|:g')"
           if [[ ! "${OVERRIDEUPHOURS}" =~ ^(${short_days}):((([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?)).{2}(([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?)))(,(${short_days}):((([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?)).{2}(([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?))))*$ ]]; then
                _log "WARNING: OVERRIDEUPHOURS is invalid: ${OVERRIDEUPHOURS}"
                unset OVERRIDEUPHOURS
           else
                for override in ${OVERRIDEUPHOURS//,/ }; do
                    [[ "${override}" =~ ^(${short_days}):((([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?)).{2}(([0-1]?[0-9]|[2][0-3])((:[0-5][0-9])?)))$ &&
                        "${BASH_REMATCH[3]}" == "${BASH_REMATCH[7]}" ]] && {
                            _log "WARNING: OVERRIDEUPHOURS invalid at: ${override}"
                            unset OVERRIDEUPHOURS
                            break; }
                done
            fi
            [ -z "${OVERRIDEUPHOURS:-}" ] &&
                _log "WARNING: Unset OVERRIDEUPHOURS"
        fi
    else
        _log "WARNING: CHECKCLOCKACTIVE is set to false. Not validating UPHOURS and OVERRIDEUPHOURS"
    fi

    if [ "${CHECKPROCNAMES}" == "true" ]; then
        local -r regex="^([A-Za-z0-9_.-]+)+(,[A-Za-z0-9_.-]+)*$"

        if [ "${LOADPROCNAMES}" == "-" ]; then
            _log "INFO: LOADPROCNAMES is disabled - No load processes being checked"
            LOADPROCNAMES=""
        elif [ -z "${LOADPROCNAMES}" ]; then
            _log "INFO: LOADPROCNAMES set to default: ${DEFAULT_LOADPROCNAMES}"
            LOADPROCNAMES="${DEFAULT_LOADPROCNAMES}"
        elif [[ ! "${LOADPROCNAMES}" =~ ${regex} ]]; then
            _log "WARNING: Invalid parameter list format: LOADPROCNAMES [lproc1,lproc2,lproc3,...]"
            _log "WARNING: You set it to '${LOADPROCNAMES}', which is not the correct syntax"
            _log "ERR: Exiting ..."
            exit 1
        fi

        if [ "${TEMPPROCNAMES}" == "-" ]; then
            _log "INFO: TEMPPROCNAMES is disabled - No temp processes being checked"
            TEMPPROCNAMES=""
        elif  [ -z "${TEMPPROCNAMES}" ]; then
            _log "INFO: TEMPPROCNAMES set to default: ${DEFAULT_TEMPPROCNAMES}"
            TEMPPROCNAMES="${DEFAULT_TEMPPROCNAMES}"
        elif [[ ! "${TEMPPROCNAMES}" =~ ${regex} ]]; then
            _log "WARNING: Invalid parameter list format: TEMPPROCNAMES [tproc1,tproc2,tproc3,...]"
            _log "WARNING: You set it to '${TEMPPROCNAMES}', which is not the correct syntax"
            _log "ERR: Exiting ..."
            exit 1
        fi
    else
        _log "WARNING: CHECKPROCNAMES is set to false. Not validating CHECKPROCNAMES and TEMPPROCNAMES"
    fi

    # Port-Numbers with at least 2 digits.
    if [ "${CHECKSOCKETS}" == "true" ]; then
        [[ "${NSOCKETNUMBERS}" =~ ^([0-9]{2,5})+(,[0-9]{2,5})*$ ]] || {
            _log "WARNING: Invalid parameter list format: NSOCKETNUMBERS [nsocket1,nsocket2,nsocket3,...]"
            _log "WARNING: Only port numbers with at least 2 digits are allowed"
            _log "WARNING: You set it to '${NSOCKETNUMBERS}', which is not the correct syntax. Maybe it's empty?"
            _log "WARNING: Setting NSOCKETNUMBERS to default: ${DEFAULT_NSOCKETNUMBERS}"
            NSOCKETNUMBERS="${DEFAULT_NSOCKETNUMBERS}"; }

        [ -n "${NSOCKETIGNORESELF:-}" ] && {
            [[ "${NSOCKETIGNORESELF}" == "true" ||
               "${NSOCKETIGNORESELF}" == "false" ]] || {
                _log "WARNING: NSOCKETIGNORESELF not set properly: ${NSOCKETIGNORESELF}"
                _log "WARNING: NSOCKETIGNORESELF has to be set to 'true' or 'false'"
                _log "WARNING: NSOCKETIGNORESELF set to default: ${DEFAULT_NSOCKETIGNORESELF}"
                NSOCKETIGNORESELF="${DEFAULT_NSOCKETIGNORESELF}"; }; }

        [ -z "${NSOCKETIGNORESELF:-}" ] &&
            NSOCKETIGNORESELF="${DEFAULT_NSOCKETIGNORESELF}"
    else
        _log "WARNING: CHECKSOCKETS is set to false. Not validating NSOCKETNUMBERS and NSOCKETIGNORESELF"
    fi

    # PINGLIST OR RANGE set-up.
    if [[ -n "${PINGLIST:-}" && -f "${PINGLIST}" ]]; then
        _log "INFO: PINGLIST is set in the config, reading IPs from: '${PINGLIST}'"
        _log "INFO: Overidding IPCHECK to: 'true'"
        unset RANGE
        IPCHECK="true"
    elif [[ -n "${PINGLIST:-}" && ! -f "${PINGLIST}" ]]; then
        _log "WARNING: PINGLIST is set in the config, but file not found: '${PINGLIST}'"
        _log "WARNING: Set IPCHECK to: 'false'"
        IPCHECK="false"
    elif [ "${IPCHECK}" == "false" ]; then
        _log "WARNING: IPCHECK is set to false. Not validating RANGE"
    elif [[ -z "${RANGE:=}" || "${RANGE}" == "-" ]]; then
        _log "WARNING: RANGE is set to '${RANGE}' -> no IP-Check"
        IPCHECK="false"
    elif [[ -n "${RANGE:-}" && ! "${RANGE}" =~ ^(([a-z]+[0-9]+[:])?(((([0-9]{1,3}\.){3})?[1-9][0-9]{0,2})|((([0-9]{1,3}\.){3})?[1-9][0-9]{0,2}\.{2}[1-9][0-9]{0,2})|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])))))(,(([a-z]+[0-9]+[:])?(((([0-9]{1,3}\.){3})?[1-9][0-9]{0,2})|((([0-9]{1,3}\.){3})?[1-9][0-9]{0,2}\.{2}[1-9][0-9]{0,2})|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]))))))*$ ]]; then
        _log "WARNING: Invalid parameter list format: ${RANGE}"
        _log "WARNING: The 'RANGE' should be comma delimited list of the following:"
        _log "WARNING: Define an IP range: start..end | iface:start..end | www.xxx.yyy.start..end | iface:xxx.yyy.zzz.start..end"
        _log "WARNING: Define a single IP: Last octet of IP zzz | www.xxx.yyy.zzz | iface:www.xxx.yyy.zzz"
        _log "WARNING: Define by FQDN: fqdn | iface:fqdn"
        _log "WARNING: If 'start..end' or 'Last octet of IP' is set the first three octets of the iface IP address are used"
        _log "WARNING: Setting RANGE to default: ${DEFAULT_RANGE}"
        RANGE="${DEFAULT_RANGE}"
    fi

    # HDDIO_RATE (max 6 digits -> 1 - 999999 kB/s).
    if [ "${HDDIOCHECK}" == "true" ]; then
        [[ "${HDDIO_RATE}" =~ ^([1-9]|[1-9][0-9]{1,5})$ ]] || {
            _log "WARNING: Invalid parameter format: HDDIO_RATE"
            _log "WARNING: You set it to '${HDDIO_RATE}', which is not the correct syntax. Maybe it's empty?"
            _log "WARNING: Set HDDIO_RATE to default: ${DEFAULT_HDDIO_RATE}"
            HDDIO_RATE="${DEFAULT_HDDIO_RATE}"; }
    else
        _log "WARNING: HDDIOCHECK is set to false. Not validating HDDIO_RATE"
    fi

    # Sleep: 1 - 9999.
    [[ "${SLEEP}" =~ ^([1-9]|[1-9][0-9]{1,3})$ ]] || {
        _log "WARNING: Invalid parameter format: SLEEP (sec)"
        _log "WARNING: You set it to '${SLEEP}', which is not the correct syntax"
        _log "WARNING: Only '1' - '9999' is allowed. Maybe it's empty?"
        _log "WARNING: Setting SLEEP to default: ${DEFAULT_SLEEP}"
        SLEEP="${DEFAULT_SLEEP}"; }

    # ULDLRATE (max 6 digits -> 1 - 999999 kB/s).
    if [ "${ULDLCHECK}" == "true" ]; then
        [[ "${ULDLRATE}" =~ ^([1-9]|[1-9][0-9]{1,5})$ ]] || {
            _log "WARNING: Invalid parameter format: ULDLRATE"
            _log "WARNING: You set it to '${ULDLRATE}', which is not the correct syntax. Maybe it's empty?"
            _log "WARNING: Set ULDLRATE to default: ${DEFAULT_ULDLRATE}"
            ULDLRATE="${DEFAULT_ULDLRATE}"; }
    else
        _log "WARNING: ULDLCHECK is set to false. Not validating ULDLRATE"
    fi

    # LOADAVERAGE (max 3 digits).
    if [ "${LOADAVERAGECHECK}" == "true" ]; then
        [[ "${LOADAVERAGE}" =~ ^([1-9]|[1-9][0-9]{1,2})$ ]] || {
            _log "WARNING: Invalid parameter format: LOADAVERAGE"
            _log "WARNING: You set it to '${LOADAVERAGE}', which is not the correct syntax. Maybe it's empty?"
            _log "WARNING: Set LOADAVERAGECHECK to default: ${DEFAULT_LOADAVERAGE}"
            LOADAVERAGE="${DEFAULT_LOADAVERAGE}"; }
    else
        _log "WARNING: LOADAVERAGECHECK is set to false. Not validating LOADAVERAGE"
    fi

    # SHUTDOWNCOMMAND - Check acpi power states with pm-is-supported.
    [ -z "${SHUTDOWNCOMMAND}" ] && {
        _log "WARNING: No shutdown command set."
        _log "WARNING: Setting it to: ${DEFAULT_SHUTDOWNCOMMAND}"
        SHUTDOWNCOMMAND="${DEFAULT_SHUTDOWNCOMMAND}"; }

    _log "INFO: SHUTDOWNCOMMAND is set to: ${SHUTDOWNCOMMAND}"
    _log "INFO: Kernel $(uname -r) supports power management modes:"
    declare -A pm_map=( ["suspend"]="--suspend:suspend to RAM" \
                        ["hibernate"]="--hibernate:suspend to DISK" \
                        ["hybrid"]="--suspend-hybrid:suspend to RAM and DISK" )
    for check in "${!pm_map[@]}"; do
        pm-is-supported "${pm_map["${check}"]%:*}" &&
            _log "INFO: Kernel supports: ${check^^} (${pm_map["${check}"]#*:})"
    done
    # Check, if shutdown hybrid, suspend and hibernate are supported.
    [[ "${SHUTDOWNCOMMAND}" =~ ^systemctl\ (hybrid|suspend|hibernate)$ ]] && {
        pm-is-supported "${pm_map["${BASH_REMATCH[1]}"]%:*}" || {
        _log "WARNING: 'SHUTDOWNCOMMAND=\"${SHUTDOWNCOMMAND}\"' not supported!"
        _log "WARNING: Setting it to default: ${DEFAULT_SHUTDOWNCOMMAND}"
        SHUTDOWNCOMMAND="${DEFAULT_SHUTDOWNCOMMAND}"; }; }

    return 0
}


###############################################################################
#
#   Name       : _check_networkconfig
#   Parameters : None
#   Globals    : $FORCE_NIC : Force network interface lookup make sure you
#                             insert a comma or space between each network
#                             interface to be checked.
#              : $NIC_TO_IP : Associative array for storing network interface
#                             to IP address mappings.
#   Return     : 0 on success.
#
_check_networkconfig() {
    _log "INFO: ------------------------------------------------------"
    _log "INFO: Finding available network interfaces and there IPv4 addresses"

    local -r net_ifaces="${FORCE_NIC:-"en,eth,wlan,bond,usb"}"
    local net_iface ip; while read -r net_iface ip; do
        local state; state="$(< "/sys/class/net/${net_iface}/operstate")"
        local ipv4_valid="true"
        [[ "${ip}" =~ ^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$ ]] ||
            ipv4_valid="false"

        [ "${DEBUG}" == "true" ] && {
            _log "DEBUG: Network interfaces: ${net_iface}"
            _log "DEBUG: Network interfaces status: ${state}"
            _log "DEBUG: Network interfaces IPv4 address: ${ip}"
            _log "DEBUG: Network interfaces IPv4 address valid: ${ipv4_valid}"; }

        [ "${ipv4_valid}" == "true" ] && [ "${state}" != "down" ] && {
            _log "INFO: '${net_iface}' has IPv4 address: ${ip}"
            NIC_TO_IP["${net_iface}"]="${ip}"; }

    done < <(LC_ALL=C ip -o -4 address show |
                awk -F"/| " -v regex=": ${net_ifaces//[, ]/|: }" \
                    '$0 ~ regex {print $2 " " $7}')

    [ -z "${!NIC_TO_IP[*]}" ] && {
        _log "ERR: No valid network interface found, exiting ..."
        exit 1; }
    return 0
}


###############################################################################
#
#   Name       : _check_system_active
#   Parameters : None
#   Globals    : $*         : All options as defined in $CONFIG for validation.
#              : $NIC_TO_IP : Associative array for storing network interface
#                             to IP address mappings.
#   Return     : 0 : If no active host has been found.
#              : 1 : If at least one active host has been found, no shutdown.
#
_check_system_active() {
    # PRIO 0: Check if time is within the STAYUP-phase e.g. 06:00 - 20:00.
    [ "${CHECKCLOCKACTIVE}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_clock()"
        _check_clock || true; }

    for net_iface in "${!NIC_TO_IP[@]}"; do
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Running on: ${net_iface}"

        # PRIO 1: Ping IP address specified across active network interfaces.
        [ "${IPCHECK}" == "true" ] && {
            [ "${DEBUG}" == "true" ] &&
                _log "DEBUG: Calling: _ping_range()"
            _ping_range "${net_iface}" \
                        "${NIC_TO_IP["${net_iface}"]}" \
                        "${NIC_TO_IP[*]}" || return 1; }

        # PRIO 2: Do a check for active network sockets.
        [ "${CHECKSOCKETS}" == "true" ] && {
            [ "${DEBUG}" == "true" ] &&
                _log "DEBUG: Calling: _check_net_status()"
            _check_net_status "${net_iface}" "${NIC_TO_IP["${net_iface}"]}" ||
                return 1; }
    done

    # PRIO 2: Do a check docker sockets for active network sockets.
    [ "${CHECKSOCKETS}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_docker_status()"
        _check_docker_status || return 1; }

    # PRIO 2: Check for connected users on the CLI.
    [ "${CHECK_CLI}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_users_cli_status()"
        _check_users_cli_status || return 1; }

    # PRIO 2: Check Samba for connected clients.
    [ "${CHECK_SAMBA}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_smb_status()"
        _check_smb_status || return 1; }

    for net_iface in "${!NIC_TO_IP[@]}"; do
        # PRIO 3: Do a check for ul-dl-rate across active network interfaces.
        [ "${ULDLCHECK}" == "true" ] && {
            [ "${DEBUG}" == "true" ] &&
                _log "DEBUG: Calling: _check_ul_dl_rate()"
            _check_ul_dl_rate "${net_iface}" || return 1; }
    done

    # PRIO 4: Do a hdd io check.
    [ "${HDDIOCHECK}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_hddio()"
        _check_hddio || return 1; }

    # PRIO 4: Do a hdd check to see if S.M.A.R.T tests are running.
    [ "${SMARTCHECK}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_smart()"
        _check_smart || return 1; }

    # PRIO 5: Do a check for some active processes.
    [ "${CHECKPROCNAMES}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_processes()"
        _check_processes || return 1; }

    # PRIO 6: Do a load average check.
    [ "${LOADAVERAGECHECK}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_loadaverage()"
        _check_loadaverage || return 1; }

    # PRIO 7: Do a PlugIn-Check for any existing files, setup in plugins.
    [ "${PLUGINCHECK}" == "true" ] && {
        [ "${DEBUG}" == "true" ] &&
            _log "DEBUG: Calling: _check_plugin()"
        _check_plugin || return 1; }

    return 0
}


###############################################################################
################# Start of body function script autoshutdown ##################
###############################################################################
_log "INFO: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" force
_log "INFO: Openmediavault-autoshutdown version: $(
    dpkg -s openmediavault-autoshutdown | awk '/Version:/{print $2}')" force
_log "INFO: Script md5sum: $(md5sum "${0}" | awk '{print $1}')" force

[ ! -f "${CONFIG}" ] && {
    _log "ERR: Config file not found! Check ${CONFIG} exits ..." force
    exit 1; }
. "${CONFIG}"
_log "INFO: ${CONFIG} loaded" force

[ ! -f "${DEFAULT_CONFIG}" ] && {
    _log "ERR: Default file not found! Check ${DEFAULT_CONFIG} exits ..." force
    exit 1; }
. <(awk '$0 !~ /^[ ]*#/ && $0 !~ /^$/{print "DEFAULT_"$0}' "${DEFAULT_CONFIG}")
_log "INFO: ${DEFAULT_CONFIG} loaded" force

# Set-up logging and modes.
[ "${FAKE:-}" == "true" ] && VERBOSE="true"
[ "${VERBOSE:-}" == "true" ] && DEBUG="true"

_check_config

# Enable / disable check here.
[ "${ENABLE}" == "false" ] && {
    _log "INFO: Script disabled by: ${CONFIG}"
    _log "INFO: Nothing to do. Exiting here ..."
    exit 0; }

_check_networkconfig

[ "${DEBUG}" == "true" ] && {
    _log "DEBUG: -----------------------------------------------------"
    for var in "CYCLES:N/A" "SLEEP:N/A" "VERBOSE:N/A" "FAKE:N/A" \
               "SHUTDOWNCOMMAND:N/A" "CHECKCLOCKACTIVE:N/A" "UPHOURS:N/A" \
               "OVERRIDEUPHOURS:N/A" "IPCHECK:N/A" "RANGE:N/A" \
               "CHECKSOCKETS:N/A" "NSOCKETNUMBERS:N/A" \
               "NSOCKETIGNORESELF:N/A" "HDDIOCHECK:N/A" "HDDIO_RATE:N/A" \
               "SMARTCHECK:N/A" "ULDLCHECK:N/A" "ULDLRATE:N/A" \
               "LOADAVERAGECHECK:N/A" "LOADAVERAGE:N/A" "LOADAVERAGE:N/A" \
               "CHECKPROCNAMES:N/A" "LOADPROCNAMES:disabled" \
               "TEMPPROCNAMES:disabled" "PLUGINCHECK:N/A"; do
        value=${var%:*}
        _log "DEBUG: ${value}: ${!value:-${var#*:}}"
    done
    _log "DEBUG: Available plugins found in: /etc/autoshutdown.d"
    for _plugin in /etc/autoshutdown.d/*; do
        [ ! -f "${_plugin}" ] || _log "DEBUG: Plugin: ${_plugin}"
    done; }

_log "INFO: --------------- Initialise states --------------------"

[ "${HDDIOCHECK}" == "true" ] && ! _check_hddio && {
    _log "ERR: Initialising _check_hddio(): Check using verbose mode"
    exit 1; }

for net_iface in "${!NIC_TO_IP[@]}"; do
    [ "${ULDLCHECK}" == "true" ] && ! _check_ul_dl_rate "${net_iface}" && {
        _log "ERR: Initialising _check_ul_dl_rate(): check using verbose mode"
        exit 1; }
done

_log "INFO: ---------------- Script started ----------------------"

if [ "${FAKE}" == "true" ]; then
    _log "INFO: FAKE-Mode in on, waiting 1 second for first check"
    sleep 1
else
    _log "INFO: Waiting 5 minuets until the first check"
    sleep 5m
fi

for net_iface in "${!NIC_TO_IP[@]}"; do
    _log "INFO: Checking NIC(s): ${net_iface} - ${NIC_TO_IP[${net_iface}]}"
done

_log "INFO: ${CYCLES} test cycles until shutdown is issued"
# Initialise the loop counter.
FCNT="${CYCLES}"
while : ; do
    _log "INFO: ------------------------------------------------------"
    _log "INFO: New supervision cycle started, checking system activity"

    # Check _check_system_active, to decide if we should shutdown or not.
    if _check_system_active; then
        # Nothing found so subtract one for FCNT and check can we shutdown.
        FCNT=$(( FCNT - 1 ))
        _log "INFO: All active check passed, ${FCNT} cycles until shutdown..."
        [ "${FCNT}" -eq 0 ] && _shutdown
    else
        # Reset count.
        FCNT="${CYCLES}"
    fi
    # Wait before checking again.
    _log "INFO: Sleep for ${SLEEP}s"
    sleep "${SLEEP}"
done
