#!/bin/bash

case "$1" in
    hibernate|suspend)
        logger -s -t "$USER autoshutdown [$$]" "hibernate/suspend: autoshutdown-script stop from /etc/pm/sleep.d/autoshutdown-restart"
        systemctl stop autoshutdown.service
    ;;

    thaw|resume)
        logger -s -t "$USER autoshutdown [$$]" "thaw/resume: autoshutdown-script restart from /etc/pm/sleep.d/autoshutdown-restart"
        systemctl restart autoshutdown.service
    ;;

    *)
        logger -s -t "$USER autoshutdown [$$]" "other: autoshutdown-script call from /etc/pm/sleep.d/autoshutdown-restart"
    ;;
esac