#!/bin/bash
FACILITY="local6"
case "${1}" in
    hibernate|suspend)
        logger -s -t "${USER} autoshutdown [$$]" -p "${FACILITY}.info" \
             "INFO: 'autoshutdown-restart(): hibernate/suspend: autoshutdown-script stop'"
    ;;
    thaw|resume)
        logger -s -t "${USER} autoshutdown [$$]" -p "${FACILITY}.info" \
            "INFO: 'autoshutdown-restart(): thaw/resume: autoshutdown-script restart'"
        systemctl restart autoshutdown.service
    ;;
    *)
        logger -s -t "${USER} autoshutdown [$$]" -p "${FACILITY}.info" \
             "INFO: 'autoshutdown-restart(): other: autoshutdown-script no action'"
    ;;
esac
